export type Platform = {
  name: string;
  link: string;
  reliability: number;
  userFriendliness: number;
  offerScope: number;
  pricePerformance: number;
  security: number;
  additionalFeatures: number;
  customerSupport: number;
  logo?: string;
};

export const platforms: Platform[] = [
  {
    name: "ImmobilienScout24",
    link: "https://www.immobilienscout24.de/",
    reliability: 90,
    userFriendliness: 95,
    offerScope: 98,
    pricePerformance: 80,
    security: 95,
    additionalFeatures: 85,
    customerSupport: 92,
  },
  {
    name: "Immowelt",
    link: "https://www.immowelt.de/",
    reliability: 85,
    userFriendliness: 90,
    offerScope: 92,
    pricePerformance: 75,
    security: 90,
    additionalFeatures: 82,
    customerSupport: 90,
  },
  {
    name: "Immonet",
    link: "https://www.immonet.de/",
    reliability: 80,
    userFriendliness: 85,
    offerScope: 89,
    pricePerformance: 70,
    security: 88,
    additionalFeatures: 80,
    customerSupport: 85,
  },
  {
    name: "eBay Kleinanzeigen",
    link: "https://www.ebay-kleinanzeigen.de/",
    reliability: 70,
    userFriendliness: 80,
    offerScope: 85,
    pricePerformance: 85,
    security: 70,
    additionalFeatures: 78,
    customerSupport: 70,
  },
  {
    name: "WG-Gesucht.de",
    link: "https://www.wg-gesucht.de/",
    reliability: 75,
    userFriendliness: 75,
    offerScope: 70,
    pricePerformance: 90,
    security: 75,
    additionalFeatures: 75,
    customerSupport: 65,
  },
  {
    name: "Wohnungsboerse.net",
    link: "https://www.wohnungsboerse.net/",
    reliability: 60,
    userFriendliness: 70,
    offerScope: 65,
    pricePerformance: 80,
    security: 80,
    additionalFeatures: 70,
    customerSupport: 60,
  },
  {
    name: "Kalaydo",
    link: "https://www.kalaydo.de/",
    reliability: 50,
    userFriendliness: 65,
    offerScope: 50,
    pricePerformance: 75,
    security: 65,
    additionalFeatures: 60,
    customerSupport: 75,
  },
  {
    name: "Ohne-Makler.net",
    link: "https://www.ohne-makler.net/",
    reliability: 65,
    userFriendliness: 85,
    offerScope: 60,
    pricePerformance: 70,
    security: 85,
    additionalFeatures: 68,
    customerSupport: 80,
  },
  {
    name: "Nestoria",
    link: "https://www.nestoria.de/",
    reliability: 78,
    userFriendliness: 88,
    offerScope: 75,
    pricePerformance: 72,
    security: 92,
    additionalFeatures: 85,
    customerSupport: 82,
  },
  {
    name: "Immosuchmaschine.de",
    link: "https://www.immosuchmaschine.de/",
    reliability: 82,
    userFriendliness: 90,
    offerScope: 80,
    pricePerformance: 78,
    security: 90,
    additionalFeatures: 88,
    customerSupport: 88,
  },
  {
    name: "Ab-ins-Zuhause",
    link: "https://www.ab-ins-zuhause.de/",
    reliability: 80,
    userFriendliness: 88,
    offerScope: 85,
    pricePerformance: 75,
    security: 85,
    additionalFeatures: 80,
    customerSupport: 85,
  },
  {
    name: "Wohnungsboerse.net (Provisionsfrei)",
    link: "https://www.wohnungsboerse.net/wohnung-mieten-provisionsfrei",
    reliability: 85,
    userFriendliness: 87,
    offerScope: 80,
    pricePerformance: 80,
    security: 80,
    additionalFeatures: 75,
    customerSupport: 80,
  },
  {
    name: "Dawonia",
    link: "https://www.dawonia.de/mieten",
    reliability: 75,
    userFriendliness: 80,
    offerScope: 70,
    pricePerformance: 85,
    security: 82,
    additionalFeatures: 85,
    customerSupport: 78,
  },
  {
    name: "GWG München",
    link: "http://www.gwg-muenchen.de/",
    reliability: 90,
    userFriendliness: 85,
    offerScope: 88,
    pricePerformance: 88,
    security: 92,
    additionalFeatures: 88,
    customerSupport: 88,
  },
  {
    name: "GEWOFAG",
    link: "https://www.gewofag.de",
    reliability: 92,
    userFriendliness: 90,
    offerScope: 85,
    pricePerformance: 90,
    security: 90,
    additionalFeatures: 82,
    customerSupport: 85,
  },
  {
    name: "Meine Stadt",
    link: "https://www.meinestadt.de/",
    reliability: 70,
    userFriendliness: 75,
    offerScope: 72,
    pricePerformance: 78,
    security: 75,
    additionalFeatures: 70,
    customerSupport: 72,
  },
  {
    name: "Wohnung Jetzt",
    link: "https://www.wohnung-jetzt.de/",
    reliability: 68,
    userFriendliness: 78,
    offerScope: 70,
    pricePerformance: 80,
    security: 78,
    additionalFeatures: 68,
    customerSupport: 70,
  },
  {
    name: "Lieblingsmieter",
    link: "https://www.lieblingsmieter.de/",
    reliability: 75,
    userFriendliness: 82,
    offerScope: 75,
    pricePerformance: 85,
    security: 85,
    additionalFeatures: 75,
    customerSupport: 75,
  },
  {
    name: "ImmobilienScout24",
    link: "https://www.immoscout24.de",
    reliability: 90,
    userFriendliness: 95,
    offerScope: 98,
    pricePerformance: 80,
    security: 95,
    additionalFeatures: 85,
    customerSupport: 92,
  },
  {
    name: "Immowelt",
    link: "https://www.immowelt.de",
    reliability: 85,
    userFriendliness: 90,
    offerScope: 92,
    pricePerformance: 75,
    security: 90,
    additionalFeatures: 82,
    customerSupport: 90,
  },
  {
    name: "IVD24",
    link: "https://www.ivd24.de",
    reliability: 82,
    userFriendliness: 88,
    offerScope: 85,
    pricePerformance: 72,
    security: 85,
    additionalFeatures: 75,
    customerSupport: 82,
  },
  {
    name: "1A-Immobilienmarkt",
    link: "https://www.1a-immobilienmarkt.de",
    reliability: 78,
    userFriendliness: 85,
    offerScope: 75,
    pricePerformance: 70,
    security: 78,
    additionalFeatures: 68,
    customerSupport: 75,
  },
  {
    name: "Wochenanzeiger",
    link: "https://www.wochenanzeiger.de",
    reliability: 65,
    userFriendliness: 70,
    offerScope: 65,
    pricePerformance: 68,
    security: 65,
    additionalFeatures: 60,
    customerSupport: 65,
  },
  {
    name: "Hallo München",
    link: "https://www.hallo-muenchen.de",
    reliability: 60,
    userFriendliness: 68,
    offerScope: 60,
    pricePerformance: 65,
    security: 62,
    additionalFeatures: 55,
    customerSupport: 60,
  },
  {
    name: "eBay Kleinanzeigen",
    link: "https://www.ebay-kleinanzeigen.de/",
    reliability: 70,
    userFriendliness: 80,
    offerScope: 85,
    pricePerformance: 85,
    security: 70,
    additionalFeatures: 78,
    customerSupport: 70,
  },
  {
    name: "Quoka",
    link: "https://www.quoka.de/",
    reliability: 55,
    userFriendliness: 60,
    offerScope: 50,
    pricePerformance: 60,
    security: 55,
    additionalFeatures: 50,
    customerSupport: 55,
  },
  {
    name: "Kalaydo",
    link: "https://www.kalaydo.de",
    reliability: 65,
    userFriendliness: 65,
    offerScope: 60,
    pricePerformance: 75,
    security: 68,
    additionalFeatures: 60,
    customerSupport: 65,
  },
  {
    name: "WG-Gesucht.de",
    link: "https://www.wg-gesucht.de",
    reliability: 75,
    userFriendliness: 75,
    offerScope: 70,
    pricePerformance: 90,
    security: 75,
    additionalFeatures: 75,
    customerSupport: 75,
  },
  {
    name: "WG-Suche",
    link: "https://www.wg-suche.de",
    reliability: 72,
    userFriendliness: 78,
    offerScope: 65,
    pricePerformance: 85,
    security: 72,
    additionalFeatures: 65,
    customerSupport: 72,
  },
  {
    name: "WG-Welt",
    link: "https://www.wg-welt.de",
    reliability: 70,
    userFriendliness: 70,
    offerScope: 60,
    pricePerformance: 70,
    security: 65,
    additionalFeatures: 60,
    customerSupport: 65,
  },
  {
    name: "WG-Cast",
    link: "https://www.wg-cast.de",
    reliability: 68,
    userFriendliness: 68,
    offerScope: 58,
    pricePerformance: 68,
    security: 62,
    additionalFeatures: 58,
    customerSupport: 60,
  },
  {
    name: "Wohngemeinschaft.de",
    link: "https://www.wohngemeinschaft.de",
    reliability: 62,
    userFriendliness: 65,
    offerScope: 55,
    pricePerformance: 60,
    security: 60,
    additionalFeatures: 55,
    customerSupport: 55,
  },
  {
    name: "Die-WG-Boerse",
    link: "https://www.die-wg-boerse.de",
    reliability: 70,
    userFriendliness: 70,
    offerScope: 68,
    pricePerformance: 75,
    security: 72,
    additionalFeatures: 65,
    customerSupport: 72,
  },
  {
    name: "Ohne-Makler.de",
    link: "https://www.ohne-makler.de",
    reliability: 85,
    userFriendliness: 85,
    offerScope: 75,
    pricePerformance: 80,
    security: 85,
    additionalFeatures: 68,
    customerSupport: 80,
  },
];
